name: Building for Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Tag
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout tools repository
        uses: actions/checkout@v3
        with:
          repository: WaterMediaTeam/tools
          path: tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK (21)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Set up Gradle 9.2.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.2.1'

      - name: Show Gradle & Java versions
        run: |
          gradle --version
          java -version

      - name: Release to CurseForge
        run: gradle publishCurseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Release to Modrinth
        run: gradle publishModrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}